# fly.toml app configuration file generated for organicnearby on 2025-07-10T11:59:02-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'organicnearby'
primary_region = 'sea'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '20'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'production'
  APP_URL = 'https://organicnearby.fly.dev'
  #ASSET_URL = 'https://organicnearby.fly.dev'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  #SESSION_DOMAIN = 'organicnearby.fly.dev'
  #SANCTUM_STATEFUL_DOMAINS = 'organicnearby.fly.dev'
  VITE_BASE_URL = 'https://organicnearby.fly.dev'
  DB_CONNECTION="sqlite"
  DB_DATABASE="/var/www/html/storage/database/database.sqlite"
  SSR_URL="127.0.0.1:13714"
  #SSR_URL="ssr.process.organicnearby.internal:13714"

[deploy]
  release_command = "php artisan migrate --force"

[processes]
  app=""

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "database"
  destination = "/var/www/html/storage/database"

[[vm]]
  size = 'shared-cpu-1x'
  memory = "1gb"
